module.exports.reviewOptions = [
  {
    posted_date: '2019-10-30',
    user_name: 'amyG',
    review_title: 'This thing is great!',
    review_text: 'Exceeded expectations. It seriously fit our home perfectly',
    overall_rating: 5,
    product_value_for_money: 5,
    product_quality: 5,
    product_appearance: 5,
    product_ease_of_assembly: 5,
    product_works_as_expected: 5,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-11-25',
    user_name: 'betty C',
    review_title: 'I love it!',
    review_text:
      'This was perfect for us. Even my mother-in-law complemented me on it(and she usually hates everything I pick)!',
    overall_rating: 5,
    product_value_for_money: 4,
    product_quality: 4,
    product_appearance: 5,
    product_ease_of_assembly: 3,
    product_works_as_expected: 5,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-12-01',
    user_name: 'Joe Pumpkin',
    review_title: 'Nice fit to our home',
    review_text:
      'Overall we are satisfied with it. However, I do wish it was easier to assemble. Must have spent three hours putting it together!',
    overall_rating: 4,
    product_value_for_money: 4,
    product_quality: 5,
    product_appearance: 4,
    product_ease_of_assembly: 2,
    product_works_as_expected: 4,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-10-18',
    user_name: 'OscarG.',
    review_title: 'So many complements!',
    review_text: "SO many people have complemented me on this item! ah! It's great!",
    overall_rating: 5,
    product_value_for_money: 5,
    product_quality: 4,
    product_appearance: 5,
    product_ease_of_assembly: 3,
    product_works_as_expected: 4,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-05-03',
    user_name: 'JD',
    review_title: 'Wearing down already',
    review_text:
      'We love the look of it, but the quality is lacking. Unfortunately, after only 6 months it is already showing wear...',
    overall_rating: 2,
    product_value_for_money: 2,
    product_quality: 1,
    product_appearance: 5,
    product_ease_of_assembly: 4,
    product_works_as_expected: 2,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 0
  },
  {
    posted_date: '2019-10-10',
    user_name: 'Elsa',
    review_title: 'Missing parts! ',
    review_text:
      'I spent four hours trying to put this together, only to realize I was missing a part! Ugh. I was able to get them, but had to return to the store.',
    overall_rating: 1,
    product_value_for_money: 3,
    product_quality: 3,
    product_appearance: 5,
    product_ease_of_assembly: 1,
    product_works_as_expected: 2,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 0
  },
  {
    posted_date: '2019-10-29',
    user_name: 'McLovin',
    review_title: 'Missing parts! ',
    review_text:
      'I spent four hours trying to put this together, only to realize I was missing a part! Ugh. I was able to get them, but had to return to the store.',
    overall_rating: 3,
    product_value_for_money: 3,
    product_quality: 3,
    product_appearance: 5,
    product_ease_of_assembly: 1,
    product_works_as_expected: 2,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-01-16',
    user_name: 'Ivan Ivanovich',
    review_title: 'Beautiful piece, but so hard to assemble. ',
    review_text:
      'I love how this looks in my home! I could not be happier with it now. But boy did it give me trouble with assembly!',
    overall_rating: 4,
    product_value_for_money: 5,
    product_quality: 4,
    product_appearance: 5,
    product_ease_of_assembly: 2,
    product_works_as_expected: 5,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-08-11',
    user_name: 'Jason Bourne',
    review_title: 'Did not end up meeting our needs.',
    review_text:
      'From the photos, I thought it would look different than it did. Not a bad product, but not suited for my needs',
    overall_rating: 2,
    product_value_for_money: 3,
    product_quality: 4,
    product_appearance: 2,
    product_ease_of_assembly: 4,
    product_works_as_expected: 2,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 0
  },
  {
    posted_date: '2019-07-18',
    user_name: 'Will Ferrell',
    review_title: 'Assembly was a breeze',
    review_text:
      'I was worried about assembling my own furniture for the first time, but their instructions were SO easy to follow! This product is great!',
    overall_rating: 5,
    product_value_for_money: 4,
    product_quality: 5,
    product_appearance: 4,
    product_ease_of_assembly: 5,
    product_works_as_expected: 4,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-09-01',
    user_name: 'Sven',
    review_title: "I'm a happy clam!",
    review_text: 'Great product, great price. IKEA for the win!',
    overall_rating: 4,
    product_value_for_money: 5,
    product_quality: 5,
    product_appearance: 4,
    product_ease_of_assembly: 5,
    product_works_as_expected: 5,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-05-19',
    user_name: 'Olaf',
    review_title: "Next time I'll order with the assembly!",
    review_text:
      "Their instructions were good, but I guess I have two left thumbs and coulnd't get all the pieces together. Finally got things together with my son's help, and I love it!",
    overall_rating: 5,
    product_value_for_money: 5,
    product_quality: 4,
    product_appearance: 4,
    product_ease_of_assembly: 2,
    product_works_as_expected: 3,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-09-03',
    user_name: 'the Mandalorian',
    review_title: 'Not a fan...',
    review_text:
      "Didn't fit my space right, and had a knick in it right out of the box. Just not for me.",
    overall_rating: 3,
    product_value_for_money: 1,
    product_quality: 2,
    product_appearance: 3,
    product_ease_of_assembly: 2,
    product_works_as_expected: 1,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 0
  },
  {
    posted_date: '2019-06-29',
    user_name: 'Kelly Clarkson',
    review_title: 'Got this as a birthday gift, and I am so pleased!',
    review_text: 'Wow! This looks looks beautiful in my house!',
    overall_rating: 5,
    product_value_for_money: 4,
    product_quality: 4,
    product_appearance: 5,
    product_ease_of_assembly: 3,
    product_works_as_expected: 4,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 1
  },
  {
    posted_date: '2019-03-12',
    user_name: 'Left Shark',
    review_title: 'OK, but feels a little cheap.',
    review_text:
      "I ordered online, and was hopigng it would feel higher quality. Alas, here we are. But it works, so I'm keeping it.",
    overall_rating: 2,
    product_value_for_money: 2,
    product_quality: 3,
    product_appearance: 3,
    product_ease_of_assembly: 4,
    product_works_as_expected: 4,
    review_helpful: 0,
    review_helpful_no: 0,
    product_recommended: 0
  }
];
